# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2025 SpacemiT Technology Co., Ltd.
#

# Use CONFIG_$(SPL_) pattern to automatically handle both U-Boot proper and SPL
obj-$(CONFIG_$(SPL_)ESPI) += espi-uclass.o
obj-$(CONFIG_$(SPL_)ESPI_SPACEMIT_K3) += espi-spacemit.o espi-spacemit-lib.o