# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2025-2026 Spacemit, Inc

obj-y	+= k3.o k3-tlvinfo.o k3-i2c-eeprom.o
obj-$(CONFIG_SPL_BUILD) += spl.o spl_extra_fit.o
obj-$(CONFIG_ENV_IS_IN_NFS) +=nfs_env.o
obj-$(CONFIG_SPLASH_SOURCE) += splash.o
