/* SPDX-License-Identifier: GPL-2.0-only OR */
/*
 * Spacemit K3 reset controller driver
 * Copyright (c) 2025, spacemit Corporation.
 */

#ifndef __DT_BINDINGS_RESET_SAPCEMIT_K3_H__
#define __DT_BINDINGS_RESET_SAPCEMIT_K3_H__
//APBC
#define RESET_UART0              0
#define RESET_UART2              1
#define RESET_UART3              2
#define RESET_UART4              3
#define RESET_UART5              4
#define RESET_UART6              5
#define RESET_UART7              6
#define RESET_UART8              7
#define RESET_UART9              8
#define RESET_UART10             9
#define RESET_GPIO               10
#define RESET_PWM0               11
#define RESET_PWM1               12
#define RESET_PWM2               13
#define RESET_PWM3               14
#define RESET_PWM4               15
#define RESET_PWM5               16
#define RESET_PWM6               17
#define RESET_PWM7               18
#define RESET_PWM8               19
#define RESET_PWM9               20
#define RESET_PWM10              21
#define RESET_PWM11              22
#define RESET_PWM12              23
#define RESET_PWM13              24
#define RESET_PWM14              25
#define RESET_PWM15              26
#define RESET_PWM16              27
#define RESET_PWM17              28
#define RESET_PWM18              29
#define RESET_PWM19              30
#define RESET_SPI0               31
#define RESET_SPI1               32
#define RESET_SPI3               33
#define RESET_RTC                34
#define RESET_TWSI0              35
#define RESET_TWSI1              36
#define RESET_TWSI2              37
#define RESET_TWSI4              38
#define RESET_TWSI5              39
#define RESET_TWSI6              40
#define RESET_TWSI8              41
#define RESET_TIMERS0            42
#define RESET_TIMERS1            43
#define RESET_TIMERS2            44
#define RESET_TIMERS3            45
#define RESET_TIMERS4            46
#define RESET_TIMERS5            47
#define RESET_TIMERS6            48
#define RESET_TIMERS7            49
#define RESET_AIB                50
#define RESET_ONEWIRE            51
#define RESET_I2S0               52
#define RESET_I2S1               53
#define RESET_I2S2               54
#define RESET_I2S3               55
#define RESET_I2S4               56
#define RESET_I2S5               57
#define RESET_DRO                58
#define RESET_IR0                59
#define RESET_IR1                60
#define RESET_TSEN               61
#define RESET_IPC_AP2AUD         62
#define RESET_CAN0               63
#define RESET_CAN1               64
#define RESET_CAN2               65
#define RESET_CAN3               66
#define RESET_CAN4               67
//MPMU
#define RESET_WDT                68
#define RESET_RIPC               69
//APMU
#define RESET_CSI                70
#define RESET_CCIC2_PHY          71
#define RESET_CCIC3_PHY          72
#define RESET_ISP                73
#define RESET_ISP_AHB            74
#define RESET_ISP_CIBUS          75
#define RESET_DSI_ESC            76
#define RESET_LCD                77
#define RESET_V2D                78
#define RESET_LCD_SPI_HBUS       79
#define RESET_LCD_SPI_BUS        80
#define RESET_LCD_MCLK           81
#define RESET_LCD_DSCCLK         82
#define RESET_SC2_HCLK           83
#define RESET_CCIC_4X            84
#define RESET_CCIC1_PHY          85
#define RESET_SDH_AXI            86
#define RESET_SDH0               87
#define RESET_SDH1               88
#define RESET_SDH2               89
#define RESET_USB2               90
#define RESET_USB3_PORTA         91
#define RESET_USB3_PORTB         92
#define RESET_USB3_PORTC         93
#define RESET_USB3_PORTD         94
#define RESET_QSPI               95
#define RESET_QSPI_BUS           96
#define RESET_DMA                97
#define RESET_AES_WTM            98
#define RESET_MCB_DCLK           99
#define RESET_MCB_ACLK           100
#define RESET_VPU                101
#define RESET_DTC                102
#define RESET_GPU                103
#define RESET_MC                 104
#define RESET_CPU0_POP           105
#define RESET_CPU0_SW            106
#define RESET_CPU1_POP           107
#define RESET_CPU1_SW            108
#define RESET_CPU2_POP           109
#define RESET_CPU2_SW            110
#define RESET_CPU3_POP           111
#define RESET_CPU3_SW            112
#define RESET_C0_MPSUB_SW        113
#define RESET_CPU4_POP           114
#define RESET_CPU4_SW            115
#define RESET_CPU5_POP           116
#define RESET_CPU5_SW            117
#define RESET_CPU6_POP           118
#define RESET_CPU6_SW            119
#define RESET_CPU7_POP           120
#define RESET_CPU7_SW            121
#define RESET_C1_MPSUB_SW        122
#define RESET_MPSUB_DBG          123
#define RESET_UCIE               124
#define RESET_RCPU               125
#define RESET_DSI4LN2_ESCCLK     126
#define RESET_DSI4LN2_LCD_SW     127
#define RESET_DSI4LN2_LCD_MCLK   128
#define RESET_DSI4LN2_LCD_DSCCLK 129
#define RESET_DSI4LN2_DPU_ACLK   130
#define RESET_DPU_ACLK           131
#define RESET_UFS_ACLK           132
#define RESET_EDP0               133
#define RESET_EDP1               134
#define RESET_PCIE_PORTA         135
#define RESET_PCIE_PORTB         136
#define RESET_PCIE_PORTC         137
#define RESET_PCIE_PORTD         138
#define RESET_PCIE_PORTE         139
#define RESET_EMAC0              140
#define RESET_EMAC1              141
#define RESET_EMAC2              142
#define RESET_ESPI               143
//DCIU
#define RESET_HDMA               144
#define RESET_DMA350             145
#define RESET_DMA350_0           146
#define RESET_DMA350_1           147
#define RESET_AXIDMA0            148
#define RESET_AXIDMA1            149
#define RESET_AXIDMA2            150
#define RESET_AXIDMA3            151
#define RESET_AXIDMA4            152
#define RESET_AXIDMA5            153
#define RESET_AXIDMA6            154
#define RESET_AXIDMA7            155
//APBC2
#define RESET_SEC_UART1          156
#define RESET_SEC_SSP2           157
#define RESET_SEC_TWSI3          158
#define RESET_SEC_RTC            159
#define RESET_SEC_TIMERS         160
#define RESET_SEC_JTAG           161
#define RESET_SEC_GPIO           162
//RCPU
#define RESET_RCPU5_RT24_CORE0   163
#define RESET_RCPU5_RT24_CORE1   164

#define RESET_NUMBER             165

#endif /* __DT_BINDINGS_RESET_SAPCEMIT_K3_H__ */
