# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o other.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
obj-$(CONFIG_SPI_NAND_GIGADEVICE) += gigadevice.o
obj-$(CONFIG_SPI_NAND_MACRONIX) += macronix.o
obj-$(CONFIG_SPI_NAND_MICRON) += micron.o
obj-$(CONFIG_SPI_NAND_TOSHIBA) += toshiba.o
obj-$(CONFIG_SPI_NAND_WINBOND) += winbond.o
