# SPDX-License-Identifier: GPL-2.0-or-later
#
# Phy supports for Spacemit k1x SoCs
#

obj-$(CONFIG_$(SPL_)PHY_SPACEMIT_K1X_USB2)	+= k1x-usb2-ci-phy.o
obj-$(CONFIG_$(SPL_)PHY_SPACEMIT_K1X_COMBPHY)	+= k1x-combphy.o
obj-$(CONFIG_$(SPL_)PHY_SPACEMIT_K3_USB3)	+= phy-k3-usb3.o
obj-$(CONFIG_$(SPL_)PHY_SPACEMIT_PCIE)		+= phy-spacemit-pcie.o
