# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_TYPEC_TCPM) += tcpm.o tcpm-uclass.o
obj-$(CONFIG_TYPEC_FUSB301) += fusb301.o
obj-$(CONFIG_TYPEC_SWITCH) += switch-uclass.o
obj-$(CONFIG_TYPEC_SWITCH_GPIO_SBU) += gpio-sbu-switch.o
