/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef __DT_BINDINGS_POWER_DOMAIN_K3_H
#define __DT_BINDINGS_POWER_DOMAIN_K3_H

#define K3_PMU_VPU_PWR_DOMAIN  0
#define K3_PMU_GPU_PWR_DOMAIN  1
#define K3_PMU_AUD_PWR_DOMAIN  2
#define K3_PMU_LCD0_PWR_DOMAIN  3
#define K3_PMU_LCD1_PWR_DOMAIN  4

#endif /* __DT_BINDINGS_POWER_DOMAIN_K3_H */
